(function(){
'use strict';
const VERSION='V16.0';
const ARC_START='2026-10-01',ARC_END='2026-12-31',ARC_LENGTH=92;
const KEY='winter_arc_tracker_v16';
const OLD_KEYS=['winter_arc_tracker_v15','progress_tracker_v14_2','progress_tracker_v14_1','progress_tracker_v14','progress_tracker_v13','progress_tracker_v12','progress_tracker_v11','progress_tracker_v10','progress_tracker_v9','progress_tracker_v8','progress_tracker_v6','progress_tracker_v5','progress_tracker_v4','progress_tracker_v3_plain'];
const CREATOR={name:'Vashu Sharmaa',role:'Data Engineer • Creator',handle:'@pandatvikas1',hero:'creator-profile.jpg',profile:'creator-profile.jpg',photo3:'creator-photo-3.jpg'};
const PRESETS=[
 {id:'exercise',name:'Gym / Exercise',icon:'🏋️',focus:'Fitness',difficulty:'Medium',small:'10 minutes'},
 {id:'study',name:'Study / Deep Work',icon:'📚',focus:'Career',difficulty:'Medium',small:'15 minutes'},
 {id:'water',name:'Drink Water',icon:'💧',focus:'Health',difficulty:'Easy',small:'1 extra glass'},
 {id:'read',name:'Read',icon:'📖',focus:'Mind',difficulty:'Easy',small:'5 pages'},
 {id:'meditation',name:'Meditation',icon:'🧘',focus:'Mind',difficulty:'Easy',small:'3 minutes'},
 {id:'sleep',name:'Sleep on Time',icon:'😴',focus:'Health',difficulty:'Medium',small:'Get ready 15 min earlier'},
 {id:'walk',name:'Walk',icon:'🚶',focus:'Fitness',difficulty:'Easy',small:'10 minutes'},
 {id:'food',name:'Healthy Food',icon:'🥗',focus:'Health',difficulty:'Medium',small:'1 healthy meal'},
 {id:'phone',name:'Less Phone',icon:'📵',focus:'Mind',difficulty:'Hard',small:'10 min less'},
 {id:'wellness',name:'Private Wellness',icon:'🔒',focus:'Personal',difficulty:'Private',small:'Small private win',private:true}
];
const MILESTONES=[{day:1,title:'First Step',sub:'Start the Arc'},{day:7,title:'First Week',sub:'7 days on the journey'},{day:14,title:'Two Weeks',sub:'Keep building'},{day:30,title:'One Month',sub:'30 days of practice'},{day:60,title:'Two Months',sub:'A longer run'},{day:90,title:'Final Stretch',sub:'Last 2 days of the Arc'},{day:92,title:'Arc Complete',sub:'Finish your 2026 Arc'}];
let state=loadState();
let view=state.onboardingDone?'today':'welcome';
const initialTab=new URLSearchParams(location.search).get('tab');
if(state.onboardingDone && ['today','week','month','arc','more','download'].includes(initialTab))view=initialTab;
let compareSnapshot=null;
let installPrompt=null;
let onboarding={step:0,name:state.name||'',focus:Array.isArray(state.focus)?state.focus.slice():[],selected:state.habits.filter(h=>!h.custom).map(x=>x.id),custom:state.habits.filter(h=>h.custom).map(clone),target:state.target||5,reminder:state.reminder||'',community:!!state.communitySync};

function cryptoRandom(){try{return crypto.randomUUID()}catch(_){return 'c-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}}
function clone(o){return JSON.parse(JSON.stringify(o))}
function defaultState(){return {version:VERSION,name:'',focus:[],habits:[],checks:{},freezeDays:{},freezeUsed:{},xp:0,target:5,reminder:'',communitySync:false,clientId:cryptoRandom(),journeyStart:null,goal:'',goalTarget:0,goalAchieved:0,dailyWins:{},smallWins:{},mood:'',energy:'',journal:{},sleep:{},notes:{},dark:false,onboardingDone:false,createdAt:new Date().toISOString(),lastSeen:null,activeRoutine:null}}
function normalize(s){
 const d=defaultState();s=Object.assign(d,s||{});
 s.habits=Array.isArray(s.habits)?s.habits:[];s.checks=s.checks||{};s.freezeDays=s.freezeDays||s.freezes||{};s.freezeUsed=s.freezeUsed||{};
 s.focus=Array.isArray(s.focus)?s.focus:[];s.journal=s.journal||{};s.sleep=s.sleep||{};s.notes=s.notes||{};s.dailyWins=s.dailyWins||{};s.smallWins=s.smallWins||{};
 s.communitySync=!!s.communitySync;s.clientId=s.clientId||cryptoRandom();s.version=VERSION;
 s.habits=s.habits.map((h,i)=>{const x=Object.assign({},h);x.id=x.id||`h-${cryptoRandom()}`;x.name=x.name||`Habit ${i+1}`;x.icon=x.icon||'✅';x.focus=x.focus||'Personal';x.difficulty=x.difficulty||'Medium';x.small=x.small||'5 minutes';x.custom=!!x.custom;if(/masturbation/i.test(x.name)){x.name='Private Wellness';x.icon='🔒';x.focus='Personal';x.difficulty='Private';x.small='Small private win';x.private=true}return x});
 return s;
}
function loadState(){
 for(const k of [KEY,...OLD_KEYS]){const raw=localStorage.getItem(k);if(raw){try{return normalize(JSON.parse(raw))}catch(_){} }}
 return defaultState();
}
function save(){state.lastSeen=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));}
function ymd(d=new Date()){const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function dateObj(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function daysBetween(a,b){return Math.round((dateObj(b)-dateObj(a))/86400000)}
function inArc(s){return s>=ARC_START&&s<=ARC_END}
function arcDay(date=ymd()){if(date<ARC_START)return 0;if(date>ARC_END)return ARC_LENGTH;return daysBetween(ARC_START,date)+1}
function completed(h,d){return !!state.checks[h.id+'|'+d]}
function isFrozen(h,d){return !!state.freezeDays[h.id+'|'+d]}
function habitStreak(h,end=ymd()){
 let s=0;let cur=dateObj(end);
 while(cur>=dateObj(ARC_START)){
  const ds=ymd(cur);
  if(ds>ymd()) {cur.setDate(cur.getDate()-1);continue}
  if(inArc(ds)&&completed(h,ds)){s++;cur.setDate(cur.getDate()-1);continue}
  if(isFrozen(h,ds)){cur.setDate(cur.getDate()-1);continue}
  break;
 }
 return s;
}
function bestStreak(h){
 const dates=Object.keys(state.checks).filter(k=>k.startsWith(h.id+'|')).map(k=>k.split('|')[1]).filter(inArc).sort();
 let best=0,run=0,last=null;for(const d of dates){if(last&&daysBetween(last,d)===1)run++;else run=1;best=Math.max(best,run);last=d}return best;
}
function habitWins(h){return Object.keys(state.checks).filter(k=>k.startsWith(h.id+'|')&&inArc(k.split('|')[1])).length}
function currentArcWinCount(){return state.habits.reduce((n,h)=>n+habitWins(h),0)}
function elapsedArcDays(){const d=arcDay();return d||0}
function arcProgress(){
 const total=Math.max(1,state.habits.length);
 const elapsed=Math.max(1,elapsedArcDays());
 if(!state.habits.length)return 0;
 if(ymd()<ARC_START)return 0;
 const earned=Math.min(currentArcWinCount(),state.habits.length*elapsed);
 return Math.round(earned/(state.habits.length*elapsed)*100);
}
function todayDone(){const t=ymd();return state.habits.filter(h=>completed(h,t)).length}
function weekScore(){const t=dateObj(ymd());let total=0,done=0;for(let i=6;i>=0;i--){const d=new Date(t);d.setDate(t.getDate()-i);const ds=ymd(d);for(const h of state.habits){total++;if(completed(h,ds))done++}}return total?Math.round(done/total*100):0}
function focusHabit(){return state.habits.slice().sort((a,b)=>{const sa=habitStreak(a),sb=habitStreak(b);if(sa!==sb)return sa-sb;return habitWins(a)-habitWins(b)})[0]||null}
function level(){return Math.floor(state.xp/100)+1}
function xpToday(){return todayDone()*10}
function nextMilestone(){const d=arcDay();return MILESTONES.find(m=>m.day>d)||MILESTONES[MILESTONES.length-1]}
function story(){if(!state.habits.length)return 'Your Arc is ready. Add a habit and make your first win.';const strongest=state.habits.slice().sort((a,b)=>habitWins(b)-habitWins(a))[0];return `Your strongest habit is ${strongest.name} with ${habitWins(strongest)} wins. Keep showing up without chasing perfect days.`}
function coach(){const n=todayDone();if(!state.habits.length)return 'Start with one small habit. One win is enough for today.';if(n===0)return 'No pressure. Pick the easiest habit and get one win.';if(n===state.habits.length)return 'Full day complete. Come back tomorrow and keep the rhythm.';return `You are ${state.habits.length-n} habit${state.habits.length-n>1?'s':''} away from a full day.`}
function toast(m){const el=document.getElementById('toast');if(!el)return;el.textContent=m;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openModal(html,onOpen){const back=document.createElement('div');back.className='modal-back open';back.innerHTML=`<div class="modal">${html}</div>`;back.addEventListener('click',e=>{if(e.target===back)back.remove()});document.body.appendChild(back);onOpen&&onOpen(back);return back}
function modalButtons(){return `<div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" data-save>Save</button></div>`}
function habitFromForm(back,existing){return {id:existing?.id||'h-'+cryptoRandom(),name:back.querySelector('#mh-name').value.trim(),icon:back.querySelector('#mh-icon').value.trim()||'✅',focus:back.querySelector('#mh-focus').value,difficulty:back.querySelector('#mh-diff').value,small:back.querySelector('#mh-small').value.trim()||'5 minutes',custom:true,private:back.querySelector('#mh-private').checked}}
function addHabitModal(existing,{onSaved}={}){
 return openModal(`<h2>${existing?'Edit':'Add'} habit</h2><div class="field"><label>Name</label><input id="mh-name" value="${esc(existing?.name||'')}" maxlength="40" placeholder="e.g. Workout"></div><div class="field"><label>Icon</label><input id="mh-icon" value="${esc(existing?.icon||'✅')}" maxlength="3"></div><div class="field"><label>Focus</label><select id="mh-focus">${['Fitness','Study','Career','Health','Mind','Money','Personal'].map(x=>`<option ${x===(existing?.focus||'Personal')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Difficulty</label><select id="mh-diff">${['Easy','Medium','Hard','Private'].map(x=>`<option ${x===(existing?.difficulty||'Medium')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Small Win</label><input id="mh-small" value="${esc(existing?.small||'5 minutes')}" maxlength="50"></div><label class="check-row"><input id="mh-private" type="checkbox" ${existing?.private?'checked':''}> Keep this habit private</label>${modalButtons()}`,
 back=>{back.querySelector('[data-close]').onclick=()=>back.remove();back.querySelector('[data-save]').onclick=()=>{const h=habitFromForm(back,existing);if(!h.name)return toast('Habit name required');if(state.habits.some(x=>x.name.toLowerCase()===h.name.toLowerCase()&&(!existing||x.id!==existing.id)))return toast('Habit already exists');if(existing)Object.assign(existing,h);else state.habits.push(h);save();back.remove();render();toast(existing?'Habit updated':'Habit added ✅');onSaved&&onSaved(h)}});
}
function toggleHabit(h,d,{small=false}={}){
 if(isTodayFuture(d)){toast('Future dates are locked');return}
 if(!inArc(d)){toast('Winter Arc starts on 1 Oct 2026');return}
 if(isFrozen(h,d)){toast('Undo the freeze first');return}
 const k=h.id+'|'+d;
 if(completed(h,d)){delete state.checks[k];state.xp=Math.max(0,state.xp-10);if(small)delete state.smallWins[k];toast('Check removed')}
 else{state.checks[k]=true;state.xp+=10;if(small)state.smallWins[k]=true;toast(small?'Small win complete ✅':'Nice! +10 XP 🔥');}
 if(d===ymd())state.dailyWins[d]=todayDone();
 save();render();cloudSync();
}
function isTodayFuture(d){return d>ymd()}
function freezeDay(h,d){
 if(!inArc(d)||isTodayFuture(d))return toast('Choose a past or today date in the Arc');
 const k=h.id+'|'+d;if(completed(h,d))return toast('Undo the win before freezing');
 if(state.freezeDays[k]){delete state.freezeDays[k];state.freezeUsed[d.slice(0,7)]=false;toast('Freeze removed')}
 else{const month=d.slice(0,7);if(state.freezeUsed[month])return toast('Monthly freeze already used');state.freezeDays[k]=true;state.freezeUsed[month]=true;toast('Streak freeze used ❄️')}
 save();render();cloudSync();
}
function deleteHabit(h){if(!confirm(`Delete ${h.name}? Existing checks remain in backup but will no longer show.`))return;state.habits=state.habits.filter(x=>x.id!==h.id);save();render();cloudSync()}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}
function exportBackup(){downloadBlob(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`winter-arc-v16-backup-${ymd()}.json`)}
function importBackup(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const incoming=normalize(JSON.parse(r.result));state=incoming;save();onboarding={...onboarding,name:state.name,focus:state.focus,selected:state.habits.filter(h=>!h.custom).map(h=>h.id),custom:state.habits.filter(h=>h.custom).map(clone),target:state.target,reminder:state.reminder,community:state.communitySync};view='today';render();toast('Backup restored ✅')}catch(_){toast('Invalid backup file')}};r.readAsText(f)};input.click()}
function csvExport(){const rows=[['Name','Focus','Wins','Best Streak','Private']];state.habits.forEach(h=>rows.push([h.name,h.focus,habitWins(h),bestStreak(h),h.private?'Yes':'No']));downloadBlob(new Blob([rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')],{type:'text/csv'}),'winter-arc-v16-habits.csv')}
function snapshot(){return {name:state.name||'Friend',day:arcDay(),progress:arcProgress(),wins:currentArcWinCount(),best:Math.max(0,...state.habits.map(bestStreak)),week:weekScore()}}
function encode(o){const bytes=new TextEncoder().encode(JSON.stringify(o));let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function decode(s){try{let x=s.replaceAll('-','+').replaceAll('_','/');while(x.length%4)x+='=';const bin=atob(x);const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}catch(_){return null}}
function shareURL(){return location.origin+location.pathname+'#compare='+encode(snapshot())}
function shareText(){const s=snapshot();return `❄️ Winter Arc 2026\nDay ${s.day}/${ARC_LENGTH} • ${s.progress}% progress\n🔥 ${s.wins} wins • Best streak ${s.best}\nBuilt by ${CREATOR.name} ${CREATOR.handle}`}
async function shareProgress(){const s=snapshot();cloudEvent('progress_shared',{arc_day:s.day,progress:s.progress});const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d');c.fillStyle='#214b54';c.fillRect(0,0,1080,1350);c.fillStyle='#173624';c.fillRect(0,760,1080,590);c.fillStyle='#a8e5bc';c.font='800 38px system-ui';c.fillText('WINTER ARC 2026',70,100);c.fillStyle='#fff';c.font='950 120px system-ui';c.fillText(`DAY ${s.day}`,70,255);c.font='800 54px system-ui';c.fillText(`${s.progress}% ARC PROGRESS`,70,345);c.font='700 44px system-ui';c.fillText(`🔥 ${s.wins} WINS`,70,430);c.fillText(`⚡ BEST STREAK ${s.best}`,70,500);c.fillText(`✅ THIS WEEK ${s.week}%`,70,570);c.font='850 48px system-ui';c.fillText(CREATOR.name,70,1125);c.font='700 35px system-ui';c.fillStyle='#b9dcc6';c.fillText(CREATOR.handle,70,1175);c.font='600 30px system-ui';c.fillText('Build your Arc. One day at a time.',70,1240);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(navigator.share){try{const file=new File([blob],'winter-arc-progress.png',{type:'image/png'});await navigator.share({title:'My Winter Arc Progress',text:shareText(),files:[file]});return}catch(_){} }downloadBlob(blob,'winter-arc-progress.png');toast('Progress card created')}
async function shareCompare(){const url=shareURL();const text=`Compare my Winter Arc progress with me ❄️\n${url}`;cloudEvent('compare_created',{arc_day:arcDay()});if(navigator.share){try{await navigator.share({title:'Winter Arc Compare',text});return}catch(_){} }try{await navigator.clipboard.writeText(url);toast('Compare link copied')}catch(_){prompt('Copy this compare link',url)}}
async function shareCompareCard(){if(!compareSnapshot)return shareCompare();const me=snapshot(),f=compareSnapshot;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d');c.fillStyle='#214b54';c.fillRect(0,0,1080,1350);c.fillStyle='#a8e5bc';c.font='800 38px system-ui';c.fillText('WINTER ARC • FRIEND COMPARE',65,95);c.fillStyle='#fff';c.font='950 64px system-ui';c.fillText(me.name,65,220);c.fillText(f.name||'Friend',590,220);c.font='800 42px system-ui';c.fillStyle='#d8eee0';c.fillText('ARC PROGRESS',65,300);c.fillText('ARC PROGRESS',590,300);c.fillStyle='#fff';c.font='950 88px system-ui';c.fillText(me.progress+'%',65,410);c.fillText((f.progress||0)+'%',590,410);c.font='700 36px system-ui';c.fillStyle='#d8eee0';c.fillText('Day '+me.day+' • '+me.wins+' wins',65,485);c.fillText('Day '+(f.day||0)+' • '+(f.wins||0)+' wins',590,485);c.font='700 34px system-ui';c.fillText('Best streak: '+me.best,65,555);c.fillText('Best streak: '+(f.best||0),590,555);c.fillText('This week: '+me.week+'%',65,615);c.fillText('This week: '+(f.week||0)+'%',590,615);c.fillStyle='#fff';c.font='850 44px system-ui';c.fillText('Progress is personal. Keep building.',65,1130);c.fillStyle='#b9dcc6';c.font='700 34px system-ui';c.fillText(CREATOR.name+'  '+CREATOR.handle,65,1190);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));cloudEvent('compare_shared',{arc_day:me.day});if(navigator.share){try{await navigator.share({title:'Winter Arc Friend Compare',text:'Compare our Winter Arc progress ❄️',files:[new File([blob],'winter-arc-compare.png',{type:'image/png'})]});return}catch(_){} }downloadBlob(blob,'winter-arc-compare.png');toast('Compare card created')}
function checkCompare(){const m=location.hash.match(/compare=([^&]+)/);compareSnapshot=m?decode(m[1]):null;if(compareSnapshot)cloudEvent('compare_opened',{friend:compareSnapshot.name||'Friend'})}
function clearCompare(){history.replaceState(null,'',location.pathname+location.search);compareSnapshot=null;render()}
async function cloudEvent(eventType,meta={}){if(!state.communitySync)return;const cfg=window.WINTER_ARC_CLOUD||{};if(!cfg.url||!cfg.anonKey)return;try{await fetch(cfg.url.replace(/\/$/,'')+'/rest/v1/community_events',{method:'POST',headers:{apikey:cfg.anonKey,Authorization:'Bearer '+cfg.anonKey,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({client_id:state.clientId,event_type:eventType,event_date:ymd(),meta})})}catch(_){} }
async function cloudSync(force=false){if(!state.communitySync&&!force)return;const cfg=window.WINTER_ARC_CLOUD||{};if(!cfg.url||!cfg.anonKey)return;const s=snapshot();const payload={client_id:state.clientId,display_name:state.name||'Anonymous',instagram_handle:state.instagramHandle||'',arc_day:s.day,arc_progress:s.progress,today_done:todayDone(),total_wins:s.wins,best_streak:s.best,week_score:s.week,joined_at:state.createdAt,last_seen:new Date().toISOString(),app_version:VERSION};try{await fetch(cfg.url.replace(/\/$/,'')+'/rest/v1/community_users?on_conflict=client_id',{method:'POST',headers:{apikey:cfg.anonKey,Authorization:'Bearer '+cfg.anonKey,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)})}catch(_){} }
function communityStatus(){const cfg=window.WINTER_ARC_CLOUD||{};return state.communitySync?(cfg.url?'Community Sync is ON':'Community Sync is ON — backend not configured yet'):'Community Sync is OFF'}
function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
function pwaStatus(){if(isStandalone())return {title:'Already installed',text:'Winter Arc Tracker is running as an app.'};if(installPrompt)return {title:'Ready to install',text:'This browser can install Winter Arc Tracker.'};return {title:'Install from your browser',text:'Use your browser menu to add Winter Arc Tracker to your home screen.'}}
function installApp(){if(isStandalone()){toast('App is already installed ✅');return}cloudEvent('install_clicked',{source:'get_app_tab'});if(installPrompt){installPrompt.prompt();installPrompt.userChoice.then(choice=>{cloudEvent('install_result',{outcome:choice.outcome});if(choice.outcome==='accepted')toast('Install accepted ✅');installPrompt=null;render()}).catch(()=>{});return}toast('Open your browser menu → Add to Home screen / Install app')}
function render(){checkCompare();document.body.classList.toggle('dark',state.dark);if(!state.onboardingDone){renderWelcome();return}renderApp()}
function renderWelcome(){
 const steps=[0,1,2,3,4,5,6],titles=['One win','Creator','Your name','Your focus','Your habits','Your rhythm','Community'];let body='';
 if(onboarding.step===0)body=`<img class="welcome-photo" src="${CREATOR.hero}" alt="Vashu Sharmaa"><div class="kicker">WINTER ARC 2026</div><h1>You don't need a perfect day.<br>You just need one win. ❄️</h1><p>Simple habits, visible progress, and your full Winter Arc from 1 Oct to 31 Dec 2026.</p><div class="hero-actions"><button class="primary" data-next>Start My Winter Arc →</button></div>`;
 else if(onboarding.step===1)body=`<div class="creator-intro"><img src="${CREATOR.hero}" alt="Vashu"><div><div class="creator-name">${CREATOR.name}</div><div class="creator-role">${CREATOR.role}</div><div class="tiny">${CREATOR.handle}</div></div></div><p style="margin-top:14px">I created Winter Arc Tracker for people who want to make daily progress simple, visible and personal.</p><div class="privacy-note">Built for small wins, honest progress and a calmer way to stay consistent.</div>${nextBack()}`;
 else if(onboarding.step===2)body=`<h2>What should we call you?</h2><div class="field"><label>Your name</label><input id="ob-name" maxlength="28" value="${esc(onboarding.name)}" placeholder="Enter your name"></div>${nextBack()}`;
 else if(onboarding.step===3)body=`<h2>What are you working on?</h2><p class="muted">Choose one or more areas.</p><div class="choice-grid">${['Fitness','Study','Career','Health','Mind','Money','Personal'].map(x=>`<button class="choice ${onboarding.focus.includes(x)?'selected':''}" data-focus="${x}">${x}</button>`).join('')}</div>${nextBack()}`;
 else if(onboarding.step===4){const custom=onboarding.custom||[];body=`<h2>Choose your habits</h2><p class="muted">Keep it realistic. You can change these later.</p><div class="choice-grid">${PRESETS.map(h=>`<button class="choice ${onboarding.selected.includes(h.id)?'selected':''}" data-preset="${h.id}">${h.icon} ${h.name}</button>`).join('')}</div>${custom.map(h=>`<div class="habit"><div class="habit-main"><div class="habit-icon">${esc(h.icon)}</div><div class="habit-body"><div class="habit-name">${esc(h.name)}</div><div class="habit-meta">${esc(h.focus)} • Custom${h.private?' • Private':''}</div></div><button class="pill" data-custom-remove="${h.id}">Remove</button></div></div>`).join('')}<button class="secondary" style="width:100%;margin-top:10px" data-add-custom>＋ Add your own habit</button>${nextBack()}`;}
 else if(onboarding.step===5)body=`<h2>Set your rhythm</h2><div class="field"><label>Daily success target</label><input id="ob-target" type="number" min="1" max="20" value="${onboarding.target}"></div><div class="field"><label>Reminder</label><select id="ob-reminder"><option value="">No reminder</option><option value="morning" ${onboarding.reminder==='morning'?'selected':''}>Morning</option><option value="afternoon" ${onboarding.reminder==='afternoon'?'selected':''}>Afternoon</option><option value="evening" ${onboarding.reminder==='evening'?'selected':''}>Evening</option></select></div>${nextBack()}`;
 else body=`<h2>Join the community?</h2><p class="muted">Optional. Your local habits and private wellness stay on your device.</p><button class="choice ${onboarding.community?'selected':''}" style="width:100%" data-community>${onboarding.community?'✅':'○'} Community Sync</button><div class="privacy-note" style="margin-top:10px">Only summary progress is shared when you turn this on. Private Wellness, journal, sleep, mood and notes are excluded.</div>${nextBack(true)}`;
 document.getElementById('app').innerHTML=`<div class="welcome"><div class="welcome-logo">Winter Arc <span>Tracker</span></div><div class="welcome-card">${body}<div class="onboard-footer"><div class="step-dots">${steps.map(i=>`<i class="step-dot ${i===onboarding.step?'on':''}" title="${titles[i]}"></i>`).join('')}</div><span class="tiny">${onboarding.step+1}/${steps.length}</span></div></div></div>`;bindWelcome();
}
function nextBack(final){return `<div class="hero-actions"><button class="secondary" data-back>Back</button><button class="primary" data-next>${final?'Build My Arc ❄️':'Continue →'}</button></div>`}
function bindWelcome(){
 const app=document.getElementById('app');
 app.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{if(onboarding.step===2){onboarding.name=app.querySelector('#ob-name').value.trim();if(!onboarding.name)return toast('Please enter your name')}if(onboarding.step===4&&!((onboarding.selected||[]).length||(onboarding.custom||[]).length))return toast('Choose at least one habit');if(onboarding.step===5){onboarding.target=Math.max(1,Math.min(20,Number(app.querySelector('#ob-target').value)||5));onboarding.reminder=app.querySelector('#ob-reminder').value}if(onboarding.step===6){finishOnboarding();return}onboarding.step++;render()});
 app.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{onboarding.step=Math.max(0,onboarding.step-1);render()});
 app.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{const x=b.dataset.focus;onboarding.focus=onboarding.focus.includes(x)?onboarding.focus.filter(v=>v!==x):onboarding.focus.concat(x);render()});
 app.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const x=b.dataset.preset;onboarding.selected=onboarding.selected.includes(x)?onboarding.selected.filter(v=>v!==x):onboarding.selected.concat(x);render()});
 app.querySelector('[data-add-custom]')?.addEventListener('click',()=>onboardingHabitModal());
 app.querySelectorAll('[data-custom-remove]').forEach(b=>b.onclick=()=>{onboarding.custom=onboarding.custom.filter(h=>h.id!==b.dataset.customRemove);render()});
 app.querySelector('[data-community]')?.addEventListener('click',()=>{onboarding.community=!onboarding.community;render()});
}
function onboardingHabitModal(){return openModal(`<h2>Add your own habit</h2><div class="field"><label>Name</label><input id="obc-name" maxlength="40" placeholder="e.g. Workout"></div><div class="field"><label>Icon</label><input id="obc-icon" maxlength="3" value="✅"></div><div class="field"><label>Focus</label><select id="obc-focus">${['Fitness','Study','Career','Health','Mind','Money','Personal'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Small Win</label><input id="obc-small" maxlength="50" value="5 minutes"></div><label class="check-row"><input id="obc-private" type="checkbox"> Keep private</label>${modalButtons()}`,b=>{b.querySelector('[data-close]').onclick=()=>b.remove();b.querySelector('[data-save]').onclick=()=>{const name=b.querySelector('#obc-name').value.trim();if(!name)return toast('Habit name required');if([...PRESETS.map(x=>x.name),...onboarding.custom.map(x=>x.name)].some(x=>x.toLowerCase()===name.toLowerCase()))return toast('Habit already exists');onboarding.custom.push({id:'c-'+cryptoRandom(),name,icon:b.querySelector('#obc-icon').value.trim()||'✅',focus:b.querySelector('#obc-focus').value, difficulty:b.querySelector('#obc-private').checked?'Private':'Medium',small:b.querySelector('#obc-small').value.trim()||'5 minutes',custom:true,private:b.querySelector('#obc-private').checked});b.remove();render()}})}
function finishOnboarding(){
 const preset=onboarding.selected.map(id=>PRESETS.find(h=>h.id===id)).filter(Boolean).map(h=>Object.assign({},h));
 const custom=(onboarding.custom||[]).map(clone);
 state.name=onboarding.name;state.focus=onboarding.focus;state.habits=[...preset,...custom];state.target=onboarding.target;state.reminder=onboarding.reminder;state.communitySync=onboarding.community;state.onboardingDone=true;state.journeyStart=ARC_START;state.createdAt=state.createdAt||new Date().toISOString();save();cloudSync();view='today';render();toast('Your Arc is ready ❄️')
}
function appTabs(){return [['today','Today','✓'],['week','Week','▤'],['month','Month','▦'],['arc','Arc','❄'],['more','More','☰'],['download','Get App','⬇']]} 
function renderApp(){const tabs=appTabs();const app=document.getElementById('app');app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="topbar-row"><button class="icon-btn" id="drawerOpen">☰</button><div class="brand">Winter Arc <span>Tracker</span></div><div style="display:flex;gap:6px"><button class="icon-btn" id="darkToggle" aria-label="Toggle theme">${state.dark?'☀':'☾'}</button><button class="icon-btn" id="profileQuick" aria-label="Open profile">${esc((state.name||'V')[0].toUpperCase())}</button></div></div></header><main class="content">${renderMain()}</main><nav class="bottom-nav">${tabs.map(t=>`<button class="${view===t[0]?'active':''}" data-view="${t[0]}"><b>${t[2]}</b>${t[1]}</button>`).join('')}</nav><button class="fab" id="addFab" aria-label="Add habit">＋</button></div><div class="drawer" id="drawer"><div class="drawer-panel"><div class="drawer-profile"><img class="avatar" src="${CREATOR.profile}" alt="Vashu"><div><b>Winter Arc Tracker</b><div class="tiny">1 Oct – 31 Dec 2026 • ${VERSION}</div></div></div><button class="menu-btn" data-menu="profile">👤 My Profile</button><button class="menu-btn" data-menu="share">📤 Share Center</button><button class="menu-btn" data-menu="habits">✓ Manage Habits</button><button class="menu-btn" data-menu="data">💾 Data & Backup</button><button class="menu-btn" data-menu="privacy">🔒 Privacy & Community</button><button class="menu-btn" data-menu="credits">❤️ Credits</button><button class="menu-btn" data-menu="settings">⚙️ Settings</button><button class="menu-btn" data-menu="coach">🧠 Daily Coach</button><div class="privacy-note" style="margin-top:18px">Progress stays on this device by default. Community Sync is optional.</div></div></div>`;bindApp()}
function renderMain(){if(compareSnapshot)return renderCompare();switch(view){case'week':return renderWeek();case'month':return renderMonth();case'arc':return renderArc();case'more':return renderMore();case'download':return renderDownload();default:return renderToday()}}
function renderToday(){const done=todayDone(),total=state.habits.length,focus=focusHabit();return `<div class="segmented">${seg()}</div><section class="section"><div class="hero"><div class="kicker">WINTER ARC 2026 • DAY ${arcDay()||'PREP'}/${ARC_LENGTH}</div><h1>${done===0?'One win can change the day.':done===total?'You showed up today. 🔥':`You are ${total-done} win${total-done!==1?'s':''} away.`}</h1><p>${esc(coach())}</p><div class="hero-actions"><button class="primary" id="shareProgress">Share my progress</button><button class="secondary" id="focusBtn">${focus?'Focus: '+esc(focus.name):'Choose a focus'}</button></div><div class="hero-credit"><img src="${CREATOR.hero}" alt="Vashu"><div><b>Built by ${CREATOR.name}</b><span>${CREATOR.role} • ${CREATOR.handle}</span></div></div></div></section><section class="section"><div class="card"><div class="section-title"><h2>Today's progress</h2><span>${done}/${total} done</span></div><div class="progress"><i style="width:${total?done/total*100:0}%"></i></div><div class="mini-grid" style="margin-top:10px"><div class="metric"><b>${weekScore()}%</b><span>This week</span></div><div class="metric"><b>🔥 ${Math.max(0,...state.habits.map(habitStreak))}</b><span>Current best</span></div><div class="metric"><b>${state.xp}</b><span>XP</span></div><div class="metric"><b>Lv ${level()}</b><span>Level</span></div></div></div></section><section class="section"><div class="section-title"><h2>Today's habits</h2><span>${state.habits.length} habits</span></div>${state.habits.length?state.habits.map(h=>habitCard(h,ymd())).join(''):'<div class="empty">No habits yet. Tap ＋ to add your first one.</div>'}</section>${focus?`<section class="section"><div class="card"><div class="section-title"><h2>Small Win</h2><span>${esc(focus.name)}</span></div><div class="muted">${esc(focus.small)}</div><button class="primary" style="margin-top:10px" data-small-win="${focus.id}">Do the small version →</button></div></section>`:''}`}
function seg(){return [['today','Today'],['week','Week'],['month','Month'],['arc','Arc']].map(([id,label])=>`<button class="${view===id?'active':''}" data-view="${id}">${label}</button>`).join('')}
function habitCard(h,d){const done=completed(h,d);return `<div class="habit"><div class="habit-main"><div class="habit-icon">${esc(h.icon)}</div><div class="habit-body"><div class="habit-name">${esc(h.name)} ${h.private?'🔒':''}</div><div class="habit-meta">🔥 ${habitStreak(h,d)} day streak • Best ${bestStreak(h)} • ${esc(h.difficulty)}</div></div><button class="check ${done?'done':''}" data-toggle="${h.id}|${d}" ${isTodayFuture(d)||!inArc(d)?'disabled':''}>${done?'✓':'○'}</button></div><div class="habit-tools"><button class="pill" data-edit="${h.id}">✎ Edit</button><button class="pill" data-freeze="${h.id}|${d}" ${!inArc(d)||isTodayFuture(d)?'disabled':''}>❄ Freeze</button><button class="pill" data-detail="${h.id}">Details</button></div></div>`}
function renderWeek(){const t=dateObj(ymd()),days=[];for(let i=6;i>=0;i--){const d=new Date(t);d.setDate(t.getDate()-i);days.push(ymd(d))}return `<div class="segmented">${seg()}</div><section class="section"><div class="card"><div class="section-title"><h2>This week</h2><span>${weekScore()}%</span></div><div class="progress"><i style="width:${weekScore()}%"></i></div>${state.habits.length?state.habits.map(h=>`<div class="habit"><div class="habit-main"><div class="habit-icon">${esc(h.icon)}</div><div class="habit-body"><div class="habit-name">${esc(h.name)}</div><div class="habit-meta">🔥 ${habitStreak(h)} days • ${habitWins(h)} Arc wins</div></div></div><div class="week-grid">${days.map(d=>`<button class="week-day ${completed(h,d)?'done':''} ${isFrozen(h,d)?'frozen':''}" data-toggle="${h.id}|${d}" ${isTodayFuture(d)||!inArc(d)?'disabled':''}>${d.slice(-2)}</button>`).join('')}</div></div>`).join(''):'<div class="empty">Add a habit to start your week.</div>'}</div></section>`}
function renderMonth(){const now=dateObj(ymd()),y=now.getFullYear(),m=now.getMonth();const totalDays=new Date(y,m+1,0).getDate();const days=Array.from({length:totalDays},(_,i)=>`${y}-${String(m+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`);return `<div class="segmented">${seg()}</div><section class="section"><div class="card"><div class="section-title"><h2>${now.toLocaleString(undefined,{month:'long',year:'numeric'})}</h2><span>${inArc(ymd())?'Arc month':'Prep'}</span></div>${state.habits.length?state.habits.map(h=>`<div class="habit"><div class="habit-main"><div class="habit-icon">${esc(h.icon)}</div><div class="habit-body"><div class="habit-name">${esc(h.name)}</div><div class="habit-meta">${habitWins(h)} Arc wins • Best ${bestStreak(h)}</div></div></div><div class="month-grid">${days.map(d=>`<button title="${d}" class="month-day ${completed(h,d)?'done':''} ${isFrozen(h,d)?'frozen':''}" data-toggle="${h.id}|${d}" ${isTodayFuture(d)||!inArc(d)?'disabled':''}></button>`).join('')}</div></div>`).join(''):'<div class="empty">Add a habit to see your month grid.</div>'}</div></section>`}
function arcMonthIndex(day){if(day<=31)return 0;if(day<=61)return 1;return 2}
function renderArc(){const day=arcDay(),upcoming=nextMilestone(),pct=arcProgress();return `<div class="segmented">${seg()}</div><section class="section"><div class="card"><div class="section-title"><div><h2>Winter Arc ❄️</h2><span>1 Oct – 31 Dec 2026</span></div><b>${day||0}/${ARC_LENGTH}</b></div><div class="progress"><i style="width:${pct}%"></i></div><div class="mini-grid" style="margin-top:10px"><div class="metric"><b>${pct}%</b><span>Arc completion</span></div><div class="metric"><b>${currentArcWinCount()}</b><span>Total wins</span></div><div class="metric"><b>🔥 ${Math.max(0,...state.habits.map(habitStreak))}</b><span>Current best</span></div><div class="metric"><b>${weekScore()}%</b><span>This week</span></div></div></div></section><section class="section"><div class="section-title"><h2>Arc Map</h2><span>${upcoming.day>day?`Next: Day ${upcoming.day}`:'Complete'}</span></div><div class="arc-rail">${['Oct','Nov','Dec'].map((m,i)=>`<div class="month-card ${day&&i===arcMonthIndex(day)?'active':''}"><div class="m">${m}</div><div class="v">${['Day 1','Day 32','Day 62'][i]}</div></div>`).join('')}<div class="month-card ${day===92?'active':''}"><div class="m">Finish</div><div class="v">Day 92</div></div></div></section><section class="section"><div class="card"><div class="section-title"><h2>Milestone Journey</h2><span>${upcoming.day>day?`Next: Day ${upcoming.day}`:'Arc complete'}</span></div><div class="timeline">${MILESTONES.map(m=>`<div class="milestone"><div class="dot ${day>=m.day?'done':''}"></div><div class="txt"><b>Day ${m.day} · ${m.title}</b><span>${m.sub}</span></div></div>`).join('')}</div></div></section><section class="section"><div class="card"><div class="section-title"><h2>Your Arc Story</h2></div><p style="line-height:1.55">${esc(story())}</p><div class="privacy-note">Recovery is part of the journey. Missed days don't erase the work you already did.</div></div></section><section class="section"><div class="card"><div class="section-title"><h2>Focus of the Arc</h2><span>${esc(focusHabit()?.focus||'Personal')}</span></div><p class="muted">${focusHabit()?`Keep ${esc(focusHabit().name)} easy enough to return to.`:'Add a habit to create your first Arc focus.'}</p>${focusHabit()?`<button class="primary" data-small-win="${focusHabit().id}">Small Win →</button>`:''}</div></section>`}
function renderCompare(){const me=snapshot(),f=compareSnapshot||{};return `<section class="section"><div class="card"><div class="section-title"><h2>Friend Compare</h2><button class="pill" id="clearCompare">Close</button></div><p class="muted">A shared progress snapshot. No winner/loser labels.</p><div class="table-wrap"><table class="compare-table"><thead><tr><th></th><th>${esc(me.name)}</th><th>${esc(f.name||'Friend')}</th></tr></thead><tbody><tr><td>Arc day</td><td>${me.day}</td><td>${f.day??'—'}</td></tr><tr><td>Progress</td><td>${me.progress}%</td><td>${f.progress??0}%</td></tr><tr><td>Total wins</td><td>${me.wins}</td><td>${f.wins??0}</td></tr><tr><td>Best streak</td><td>${me.best}</td><td>${f.best??0}</td></tr><tr><td>This week</td><td>${me.week}%</td><td>${f.week??0}%</td></tr></tbody></table></div><div class="hero-actions"><button class="primary" id="shareCompare">Share compare</button><button class="secondary" id="clearCompare2">Done</button></div></div></section>`}
function renderMore(){return `<div class="segmented">${seg()}</div><section class="section"><div class="card"><div class="creator-intro"><img src="${CREATOR.profile}" alt="Vashu"><div><div class="creator-name">${esc(state.name||'My Profile')}</div><div class="creator-role">Level ${level()} • ${state.xp} XP</div><a class="link" href="https://instagram.com/pandatvikas1" target="_blank" rel="noreferrer">${CREATOR.handle}</a></div></div></div></section><section class="section"><div class="card"><div class="section-title"><h2>Quick actions</h2></div><div class="choice-grid"><button class="choice" data-menu="share">📤 Share Center</button><button class="choice" data-menu="habits">✓ Manage Habits</button><button class="choice" data-menu="profile">👤 Profile</button><button class="choice" data-menu="data">💾 Backup & CSV</button><button class="choice" data-menu="privacy">🔒 Privacy</button><button class="choice" data-menu="credits">❤️ Credits</button><button class="choice" data-menu="settings">⚙️ Settings</button><button class="choice" data-menu="coach">🧠 Daily Coach</button></div></div></section>`}
function renderDownload(){const s=pwaStatus();return `<div class="segmented">${seg()}</div><section class="section"><div class="hero download-hero"><div class="kicker">GET THE APP</div><h1>Keep Winter Arc on your phone. 📱</h1><p>First use the GitHub Pages app normally. When your browser supports installation, install it as a standalone app.</p><div class="install-status"><span class="status-dot ${isStandalone()?'on':''}"></span><div><b>${esc(s.title)}</b><div class="tiny">${esc(s.text)}</div></div></div><div class="hero-actions"><button class="primary" id="installBtn">${isStandalone()?'App Installed ✅':installPrompt?'Install App':'How to Install'}</button><a class="secondary btn-link" href="https://github.com/Vikas915577/Tracker/releases" target="_blank" rel="noreferrer">Open APK Releases ↗</a></div></div></section><section class="section"><div class="card"><div class="section-title"><h2>Android / Chrome</h2><span>Recommended</span></div><p class="muted">Tap Install App when the button is available. Otherwise open the browser ⋮ menu and choose <b>Install app</b> or <b>Add to Home screen</b>.</p></div></section><section class="section"><div class="card"><div class="section-title"><h2>iPhone / Safari</h2><span>Home Screen</span></div><p class="muted">Open the app in Safari → Share → <b>Add to Home Screen</b>. iPhone may not show the same install prompt as Chrome.</p></div></section><section class="section"><div class="card"><div class="section-title"><h2>What is included</h2></div><div class="mini-grid"><div class="metric"><b>V16</b><span>Current app</span></div><div class="metric"><b>92</b><span>Arc days</span></div><div class="metric"><b>100%</b><span>Local tracking</span></div><div class="metric"><b>${VERSION}</b><span>Build</span></div></div><p class="tiny muted" style="margin-top:12px">“Open APK Releases” is a transparent GitHub Releases link. An APK is shown there only when a real release has been uploaded.</p></div></section>`}
function bindApp(){
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
 document.getElementById('drawerOpen').onclick=()=>document.getElementById('drawer').classList.add('open');
 document.getElementById('drawer').onclick=e=>{if(e.target.id==='drawer')e.currentTarget.classList.remove('open')};
 document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{document.getElementById('drawer').classList.remove('open');openMenu(b.dataset.menu)});
 document.getElementById('darkToggle').onclick=()=>{state.dark=!state.dark;save();render()};
 document.getElementById('profileQuick').onclick=()=>openMenu('profile');
 document.getElementById('addFab').onclick=()=>addHabitModal();
 document.getElementById('shareProgress')?.addEventListener('click',shareProgress);
 document.getElementById('focusBtn')?.addEventListener('click',()=>toast(focusHabit()?`Focus on ${focusHabit().name}`:'Add a habit first'));
 document.getElementById('clearCompare')?.addEventListener('click',clearCompare);document.getElementById('clearCompare2')?.addEventListener('click',clearCompare);document.getElementById('shareCompare')?.addEventListener('click',shareCompareCard);
 document.getElementById('installBtn')?.addEventListener('click',installApp);
 document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const [id,d]=b.dataset.toggle.split('|');const h=state.habits.find(x=>x.id===id);if(h)toggleHabit(h,d)});
 document.querySelectorAll('[data-freeze]').forEach(b=>b.onclick=()=>{const [id,d]=b.dataset.freeze.split('|');const h=state.habits.find(x=>x.id===id);if(h)freezeDay(h,d)});
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const h=state.habits.find(x=>x.id===b.dataset.edit);if(h)addHabitModal(h)});
 document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openMenu('habitDetail',b.dataset.detail));
 document.querySelectorAll('[data-small-win]').forEach(b=>b.onclick=()=>{const h=state.habits.find(x=>x.id===b.dataset.smallWin);if(h)toggleHabit(h,ymd(),{small:true})});
}
function openMenu(type,arg){if(type==='share')return shareCenter();if(type==='habits')return manageHabits();if(type==='profile')return profileModal();if(type==='data')return dataModal();if(type==='privacy')return privacyModal();if(type==='credits')return creditsModal();if(type==='settings')return settingsModal();if(type==='coach')return openModal(`<h2>🧠 Daily Coach</h2><p style="line-height:1.6">${esc(coach())}</p><button class="primary" data-close>Done</button>`,b=>b.querySelector('[data-close]').onclick=()=>b.remove());if(type==='habitDetail'){const h=state.habits.find(x=>x.id===arg);if(h)habitDetail(h)}}
function shareCenter(){openModal(`<h2>📤 Share Center</h2><p class="muted">Create a progress card or a shareable comparison snapshot.</p><div class="share-card-preview"><div><div class="kicker">WINTER ARC 2026</div><div class="big">DAY ${arcDay()}</div><p>${arcProgress()}% progress • ${currentArcWinCount()} wins</p></div><div><b>${CREATOR.name}</b><div class="handle">${CREATOR.handle}</div></div></div><div class="share-actions" style="margin-top:10px"><button class="primary" id="shareCard">Share Progress Card</button><button class="secondary" id="compareLink">Compare With Friend</button><button class="secondary" id="copyLink">Copy Compare Link</button><button class="secondary" id="inviteLink">Invite a Friend</button></div>`,back=>{back.querySelector('#shareCard').onclick=()=>shareProgress();back.querySelector('#compareLink').onclick=()=>shareCompare();back.querySelector('#copyLink').onclick=()=>shareCompare();back.querySelector('#inviteLink').onclick=async()=>{const u=location.origin+location.pathname+'?invite='+encodeURIComponent(state.clientId)+'&from='+encodeURIComponent(CREATOR.handle);cloudEvent('invite_created',{from:CREATOR.handle});if(navigator.share){try{await navigator.share({title:'Join my Winter Arc',text:`Join my Winter Arc ❄️\n${u}`});return}catch(_){} }try{await navigator.clipboard.writeText(u);toast('Invite link copied')}catch(_){prompt('Copy invite link',u)}}})}
function manageHabits(){openModal(`<h2>Manage Habits</h2>${state.habits.length?state.habits.map(h=>`<div class="habit"><div class="habit-main"><div class="habit-icon">${esc(h.icon)}</div><div class="habit-body"><div class="habit-name">${esc(h.name)} ${h.private?'🔒':''}</div><div class="habit-meta">${esc(h.focus)} • ${esc(h.difficulty)}</div></div><button class="pill" data-man-edit="${h.id}">Edit</button></div></div>`).join(''):'<div class="empty">No habits yet.</div>'}<button class="primary" style="width:100%;margin-top:10px" id="newH">＋ Add Habit</button>`,back=>{back.querySelector('#newH').onclick=()=>{back.remove();addHabitModal()};back.querySelectorAll('[data-man-edit]').forEach(b=>b.onclick=()=>{const h=state.habits.find(x=>x.id===b.dataset.manEdit);back.remove();addHabitModal(h)})})}
function profileModal(){openModal(`<div class="creator-intro"><img src="${CREATOR.hero}" alt="Vashu"><div><div class="creator-name">${esc(state.name)}</div><div class="creator-role">Level ${level()} • ${state.xp} XP</div><a class="link" href="https://instagram.com/pandatvikas1" target="_blank" rel="noreferrer">${CREATOR.handle}</a></div></div><div class="mini-grid" style="margin-top:14px"><div class="metric"><b>${arcProgress()}%</b><span>Arc progress</span></div><div class="metric"><b>${currentArcWinCount()}</b><span>Wins</span></div><div class="metric"><b>${Math.max(0,...state.habits.map(bestStreak))}</b><span>Best streak</span></div><div class="metric"><b>${arcDay()}</b><span>Arc day</span></div></div>${modalButtons()}`,back=>{back.querySelector('[data-close]').onclick=()=>back.remove();back.querySelector('[data-save]').onclick=()=>back.remove()})}
function dataModal(){openModal(`<h2>💾 Your Data</h2><p class="muted">Your backup stays on your device until you export it.</p><div class="choice-grid"><button class="choice" id="backup">⬇️ Backup JSON</button><button class="choice" id="restore">⬆️ Restore JSON</button><button class="choice" id="csv">📄 Export CSV</button><button class="choice" id="reset">♻️ Reset App</button></div>`,b=>{b.querySelector('#backup').onclick=exportBackup;b.querySelector('#restore').onclick=importBackup;b.querySelector('#csv').onclick=csvExport;b.querySelector('#reset').onclick=()=>{if(confirm('Reset all local app data?')){localStorage.removeItem(KEY);location.reload()}}})}
function privacyModal(){openModal(`<h2>🔒 Privacy & Community</h2><p>${esc(communityStatus())}</p><div class="privacy-note">Only progress summary data is sent when Community Sync is ON. Private Wellness, journal, sleep, mood and notes are excluded.</div><button class="choice" style="width:100%;margin-top:12px" id="syncToggle">${state.communitySync?'✅ Turn Community Sync OFF':'○ Turn Community Sync ON'}</button><p class="tiny" style="margin-top:10px">The public site needs the Supabase project URL and public anon key in <code>cloud-config.js</code> before cloud features can send data.</p>`,b=>b.querySelector('#syncToggle').onclick=()=>{state.communitySync=!state.communitySync;save();if(state.communitySync)cloudSync();b.remove();render()})}
function creditsModal(){openModal(`<div class="creator-intro"><img src="${CREATOR.hero}" alt="Vashu Sharmaa"><div><div class="creator-name">Vashu Sharmaa</div><div class="creator-role">Data Engineer • Creator</div><a class="link" href="https://instagram.com/pandatvikas1" target="_blank" rel="noreferrer">${CREATOR.handle}</a></div></div><p style="line-height:1.6">I created Winter Arc Tracker for people who want to make daily progress simple, visible and personal.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><img src="${CREATOR.profile}" style="width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:18px" alt="Vashu"><img src="${CREATOR.photo3}" style="width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:18px" alt="Vashu"></div><div class="hero-actions"><a class="primary btn-link" href="https://instagram.com/pandatvikas1" target="_blank" rel="noreferrer">Instagram ↗</a><button class="secondary" data-close>Done</button></div>`,b=>b.querySelector('[data-close]').onclick=()=>b.remove())}
function settingsModal(){openModal(`<h2>⚙️ Settings</h2><div class="field"><label>Your display name</label><input id="set-name" value="${esc(state.name)}"></div><div class="field"><label>Your Instagram (optional)</label><input id="set-instagram" value="${esc(state.instagramHandle||'')}" placeholder="@yourhandle"></div><div class="field"><label>Goal</label><input id="set-goal" value="${esc(state.goal)}" placeholder="e.g. Build a consistent study routine"></div><div class="field"><label>Goal target</label><input id="set-target" type="number" min="0" value="${state.goalTarget||0}"></div>${modalButtons()}`,b=>{b.querySelector('[data-close]').onclick=()=>b.remove();b.querySelector('[data-save]').onclick=()=>{state.name=b.querySelector('#set-name').value.trim()||state.name;state.instagramHandle=b.querySelector('#set-instagram').value.trim();state.goal=b.querySelector('#set-goal').value.trim();state.goalTarget=Math.max(0,Number(b.querySelector('#set-target').value)||0);save();cloudSync();b.remove();render()}})}
function habitDetail(h){openModal(`<h2>${esc(h.icon)} ${esc(h.name)}</h2><div class="mini-grid"><div class="metric"><b>${habitWins(h)}</b><span>Arc wins</span></div><div class="metric"><b>${habitStreak(h)}</b><span>Current streak</span></div><div class="metric"><b>${bestStreak(h)}</b><span>Best streak</span></div><div class="metric"><b>${esc(h.focus)}</b><span>Focus</span></div></div><p class="muted" style="margin-top:14px">Small Win: ${esc(h.small)}</p><div class="hero-actions"><button class="primary" id="hdEdit">Edit</button><button class="secondary" id="hdDelete">Delete</button></div>`,b=>{b.querySelector('#hdEdit').onclick=()=>{b.remove();addHabitModal(h)};b.querySelector('#hdDelete').onclick=()=>{b.remove();deleteHabit(h)}})}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(view==='download')render()});
window.addEventListener('appinstalled',()=>{installPrompt=null;cloudEvent('app_installed',{source:'browser'});toast('Winter Arc installed ✅');if(view==='download')render()});
if(!new URLSearchParams(location.search).has('test'))setInterval(()=>{if(!state.onboardingDone||!state.reminder)return;const h=new Date().getHours();const hit=(state.reminder==='morning'&&h===9)||(state.reminder==='afternoon'&&h===15)||(state.reminder==='evening'&&h===20);if(hit&&ymd()!==localStorage.getItem('wa_reminder')){localStorage.setItem('wa_reminder',ymd());toast('A small win is waiting for you ❄️')}},30000);
window.addEventListener('hashchange',()=>{checkCompare();render()});
if(new URLSearchParams(location.search).get('invite')&&state.onboardingDone)cloudEvent('invite_opened',{from:new URLSearchParams(location.search).get('from')||''});
// Migrate V15+ legacy state into V16 storage without losing data.
save();
cloudSync();
render();
})();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{}));}
